version: "3.8"

services:
  frontend:
    build: ./FEC-Project-main
    ports: 
      - 3000:3000
  backend:
    build: .
    ports:
      - 80:4000
    environment:
      DB_URL: mongodb+srv://sdc:Password123@cluster0.y1apv.mongodb.net/overview