version: "3.8"

services:
  app:
    build: .
    ports:
      - 4000:4000
    environment:
      DB_URL: 'mongodb://db/overview'
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes: 
      - products-api:/data/db

volumes: 
  products-api: 